/**
 * Mock Data for Admin Dashboard
 *
 * This file provides realistic sample data for all dashboard entities.
 * Data shapes here represent the UI-side normalized schema — NOT backend schemas.
 *
 * FUTURE INTEGRATION:
 * When backend APIs stabilize, the dataAdapter.js transform layer will
 * map backend responses into these same shapes. This file then becomes
 * the fallback/offline data source only.
 */

export const mockComplaints = [
    {
        id: 'C-1001',
        title: 'Broken streetlight on MG Road',
        category: 'Infrastructure',
        status: 'Open',
        priority: 'High',
        zone: 'Zone A — Central',
        department: 'Public Works',
        reportedAt: '2026-02-25T10:30:00Z',
        reportedBy: 'Rajesh Kumar',
        description: 'The streetlight near MG Road junction has been non-functional for 3 days. Pedestrians face difficulty crossing at night.',
        location: 'MG Road Junction, Sector 12',
    },
    {
        id: 'C-1002',
        title: 'Overflowing garbage bin at Market Square',
        category: 'Sanitation',
        status: 'In Progress',
        priority: 'Critical',
        zone: 'Zone B — East',
        department: 'Sanitation',
        reportedAt: '2026-02-24T08:15:00Z',
        reportedBy: 'Priya Sharma',
        description: 'Large garbage bin outside the market has been overflowing for 2 days. Strong odor affecting nearby shops.',
        location: 'Market Square, Block 4',
    },
    {
        id: 'C-1003',
        title: 'Water pipeline leakage near School',
        category: 'Water Supply',
        status: 'Open',
        priority: 'Critical',
        zone: 'Zone C — West',
        department: 'Water Department',
        reportedAt: '2026-02-24T14:00:00Z',
        reportedBy: 'Amit Patel',
        description: 'Continuous water leakage from a main pipeline near City Public School. Water wastage is significant.',
        location: 'Near City Public School, Sector 7',
    },
    {
        id: 'C-1004',
        title: 'Pothole causing accidents at Ring Road',
        category: 'Roads',
        status: 'Assigned',
        priority: 'High',
        zone: 'Zone A — Central',
        department: 'Public Works',
        reportedAt: '2026-02-23T16:45:00Z',
        reportedBy: 'Suresh Reddy',
        description: 'A large pothole on Ring Road near the flyover has caused multiple minor accidents. Urgently needs repair.',
        location: 'Ring Road, near Flyover Crossing',
    },
    {
        id: 'C-1005',
        title: 'Illegal construction in residential area',
        category: 'Building Violation',
        status: 'Pending',
        priority: 'Medium',
        zone: 'Zone D — North',
        department: 'Urban Planning',
        reportedAt: '2026-02-22T11:20:00Z',
        reportedBy: 'Meena Desai',
        description: 'Unauthorized construction extending beyond approved boundary in a residential zone.',
        location: 'Plot 42, Residential Layout, Sector 15',
    },
    {
        id: 'C-1006',
        title: 'Noise complaint from warehouse district',
        category: 'Noise',
        status: 'Resolved',
        priority: 'Low',
        zone: 'Zone B — East',
        department: 'Environment',
        reportedAt: '2026-02-21T09:00:00Z',
        reportedBy: 'Deepak Joshi',
        description: 'Excessive noise from a warehouse loading dock during nighttime hours.',
        location: 'Warehouse District, Block 9',
    },
    {
        id: 'C-1007',
        title: 'Damaged park bench in Central Garden',
        category: 'Parks',
        status: 'Closed',
        priority: 'Low',
        zone: 'Zone A — Central',
        department: 'Parks & Recreation',
        reportedAt: '2026-02-20T13:30:00Z',
        reportedBy: 'Kavita Nair',
        description: 'Two park benches in Central Garden are broken and have exposed nails.',
        location: 'Central Garden, Main Entrance',
    },
    {
        id: 'C-1008',
        title: 'Traffic signal malfunction at 4-way junction',
        category: 'Traffic',
        status: 'In Progress',
        priority: 'High',
        zone: 'Zone C — West',
        department: 'Traffic Management',
        reportedAt: '2026-02-25T07:00:00Z',
        reportedBy: 'Ravi Khanna',
        description: 'Traffic signal at the 4-way junction is stuck on green for all directions. Very dangerous.',
        location: '4-Way Junction, Main Highway Crossing',
    },
    {
        id: 'C-1009',
        title: 'Stray dogs menace near public park',
        category: 'Animal Control',
        status: 'Open',
        priority: 'Medium',
        zone: 'Zone D — North',
        department: 'Animal Control',
        reportedAt: '2026-02-24T18:00:00Z',
        reportedBy: 'Anitha Iyer',
        description: 'Pack of stray dogs near Freedom Park is aggressive towards joggers in the morning.',
        location: 'Freedom Park, North Gate',
    },
    {
        id: 'C-1010',
        title: 'Open manhole on footpath',
        category: 'Infrastructure',
        status: 'Open',
        priority: 'Critical',
        zone: 'Zone A — Central',
        department: 'Public Works',
        reportedAt: '2026-02-26T06:30:00Z',
        reportedBy: 'Vikram Singh',
        description: 'Manhole cover missing on the main footpath. Extremely dangerous for pedestrians.',
        location: 'Main Footpath, Sector 3',
    },
    {
        id: 'C-1011',
        title: 'Street flooding after light rain',
        category: 'Drainage',
        status: 'Assigned',
        priority: 'High',
        zone: 'Zone B — East',
        department: 'Water Department',
        reportedAt: '2026-02-23T20:00:00Z',
        reportedBy: 'Nandini Rao',
        description: 'Even light rain causes significant waterlogging on 2nd Main Road due to blocked drainage.',
        location: '2nd Main Road, Sector 8',
    },
    {
        id: 'C-1012',
        title: 'Faded road markings at school zone',
        category: 'Roads',
        status: 'Pending',
        priority: 'Medium',
        zone: 'Zone C — West',
        department: 'Traffic Management',
        reportedAt: '2026-02-22T15:00:00Z',
        reportedBy: 'Sunita Mehta',
        description: 'Zebra crossing and speed limit markings near the school are completely faded. Children at risk.',
        location: 'School Zone, 5th Cross Road',
    },
];

export const mockZones = [
    { id: 'Z-01', name: 'Zone A — Central', area: '12.5 sq km', activeComplaints: 15, totalComplaints: 42, status: 'Active', head: 'R. Venkatesh' },
    { id: 'Z-02', name: 'Zone B — East', area: '18.3 sq km', activeComplaints: 9, totalComplaints: 31, status: 'Active', head: 'S. Patil' },
    { id: 'Z-03', name: 'Zone C — West', area: '15.7 sq km', activeComplaints: 11, totalComplaints: 28, status: 'Active', head: 'M. Krishnamurthy' },
    { id: 'Z-04', name: 'Zone D — North', area: '22.1 sq km', activeComplaints: 7, totalComplaints: 19, status: 'Active', head: 'A. Gupta' },
    { id: 'Z-05', name: 'Zone E — South', area: '9.8 sq km', activeComplaints: 3, totalComplaints: 12, status: 'Inactive', head: 'P. Ranganath' },
];

export const mockDepartments = [
    { id: 'D-01', name: 'Public Works', head: 'K. Srinivas', activeComplaints: 12, avgResolutionTime: '3.2 days', staff: 45 },
    { id: 'D-02', name: 'Sanitation', head: 'L. Deshpande', activeComplaints: 8, avgResolutionTime: '1.5 days', staff: 62 },
    { id: 'D-03', name: 'Water Department', head: 'V. Raghavan', activeComplaints: 6, avgResolutionTime: '2.8 days', staff: 38 },
    { id: 'D-04', name: 'Traffic Management', head: 'N. Prakash', activeComplaints: 5, avgResolutionTime: '4.1 days', staff: 27 },
    { id: 'D-05', name: 'Urban Planning', head: 'B. Choudhary', activeComplaints: 3, avgResolutionTime: '7.5 days', staff: 18 },
    { id: 'D-06', name: 'Environment', head: 'S. Sundaram', activeComplaints: 2, avgResolutionTime: '2.0 days', staff: 15 },
    { id: 'D-07', name: 'Parks & Recreation', head: 'J. Mhatre', activeComplaints: 4, avgResolutionTime: '5.3 days', staff: 22 },
    { id: 'D-08', name: 'Animal Control', head: 'R. Hegde', activeComplaints: 3, avgResolutionTime: '1.8 days', staff: 12 },
];

export const mockOverviewStats = {
    totalComplaints: 127,
    openComplaints: 34,
    inProgressComplaints: 28,
    resolvedComplaints: 65,
    trends: {
        total: { direction: 'up', value: '+12%' },
        open: { direction: 'down', value: '-8%' },
        inProgress: { direction: 'up', value: '+5%' },
        resolved: { direction: 'up', value: '+18%' },
    },
};
